image: docker

services:
    - docker:dind

stages:
    - deploy

variables:
    PROJECT_ROOT_DIR: /var/www/$CI_PROJECT_NAME

before_script:
    - sudo apt-get install -y build-essential
    - sudo usermod -aG 1000 gitlab-runner
    - sudo mkdir -p $PROJECT_ROOT_DIR
    - sudo cp -a $CI_PROJECT_DIR/. $PROJECT_ROOT_DIR
    - sudo chown -R 1000:1000 $PROJECT_ROOT_DIR
    - sudo chmod g+w -R $PROJECT_ROOT_DIR

deploy-staging:
    stage: deploy
    environment:
        name: staging
        url: https://hellotaxi.greatbear.tech
    only:
        - staging
    tags:
        - staging
    script:
        - cd $PROJECT_ROOT_DIR
        - make server-down
        - make clean install
        - make migrate
        - make server
